#!/bin/sh

userresources="$HOME"/.config/X11/Xresources
if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

setxkbmap -layout hu
xbindkeys -f "$HOME"/.config/X11/xbindkeysrc
xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
xset r rate 250 30
fehbg &
pactl set-default-sink alsa_output.pci-0000_00_1f.3.analog-stereo
pactl set-default-source alsa_output.pci-0000_00_1f.3.analog-stereo.monitor

autostart="dunst udiskie picom"

# if laptop
read -r CHASSIS_TYPE < /sys/class/dmi/id/chassis_type
if [ "$CHASSIS_TYPE" = 9 ] || [ "$CHASSIS_TYPE" = 10 ]; then
    autostart="${autostart} batsignal libinput-gestures"
fi

for program in $autostart; do
	pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"

