background {
    color = rgba(0, 0, 0, 1.0)
}

label {
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    font_size = 64
    position = 0, 50
    halign = center
    valign = center
}

input-field {
    size = 300, 50
    outline_thickness = 2
    position = 0, -50
    halign = center
    valign = center
}

