require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.mason"
require "user.lsp"
require "user.treesitter"
require "user.autopairs"
require "user.impatient"
require "user.indent_blankline"
require "user.colorizer"

