[[themes]]
name = "snazzy"
[themes.palette]
background = "#282a36"
foreground = "#eff0eb"
black = "#282a36"
blue = "#57c7ff"
cyan = "#9aedfe"
green = "#5af78e"
magenta = "#ff6ac1"
red = "#ff5c57"
white = "#f1f1f0"
yellow = "#f3f99d"
bright_black = "#4a4c58"
bright_blue = "#57c7ff"
bright_cyan = "#9aedfe"
bright_green = "#5af78e"
bright_magenta = "#ff6ac1"
bright_red = "#ff5c57"
bright_white = "#f1f1f0"
bright_yellow = "#f3f99d"
selection_background = "#313244"
selection_foreground = "#feffff"

